// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKguWmYO57nTIXnA8hM-eJulrepHOG_y0',
    appId: '1:96525456223:web:42d3ef06c6d0ffa2c8dcea',
    messagingSenderId: '96525456223',
    projectId: 'toplamda-54eb5',
    authDomain: 'toplamda-54eb5.firebaseapp.com',
    storageBucket: 'toplamda-54eb5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmR45tqMuuIMp5DnOzsmwANjhZ6f7U12w',
    appId: '1:96525456223:android:2e13ee5dc90e5184c8dcea',
    messagingSenderId: '96525456223',
    projectId: 'toplamda-54eb5',
    storageBucket: 'toplamda-54eb5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKSGohte-be463SuuVFrLTRDt0cajQN-g',
    appId: '1:96525456223:ios:c74dcc1dde0c34e3c8dcea',
    messagingSenderId: '96525456223',
    projectId: 'toplamda-54eb5',
    storageBucket: 'toplamda-54eb5.appspot.com',
    iosBundleId: 'com.toplamda.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKSGohte-be463SuuVFrLTRDt0cajQN-g',
    appId: '1:96525456223:ios:c74dcc1dde0c34e3c8dcea',
    messagingSenderId: '96525456223',
    projectId: 'toplamda-54eb5',
    storageBucket: 'toplamda-54eb5.appspot.com',
    iosBundleId: 'com.toplamda.app',
  );
}
